### ISSUE TITLE
Xcode 9 support

### ISSUE THREAD

**Issue by darktears** [nrbrook/MakeXcodePluginsWork#7]
I'm trying to use the Xcode 9 beta 3 and it doesn't seem to work. I run the script like I usually do for Xcode 8 but the plugins are not loaded.

**Comment by nrbrook** [comment]
Hi, thanks for reporting, why did you close the issue? Was it a mistake?

**Comment by darktears** [comment]
No actually it works it's just that all my plugins do not work so I thought they were not activated. For example SCXcodeMinimap or Polychromatic doesn't work as they should most likely because Apple rewrote the code editor part as they said in WWDC.
